package com.konecta.stores_stock_service.common.storage;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

/**
 * Stand-in for {@link S3ObjectStorageService} while there's no usable AWS
 * account (suspended 2026-09-15 — see context.md) — stores files on local
 * disk instead of S3, and hands out URLs pointing back at this same
 * service's own {@link MediaController} instead of presigned S3 URLs. Same
 * {@link ObjectStorageService} contract either way, so nothing above this
 * layer (controllers, S3KeyFactory, callers) needed to change.
 * <p>
 * Deliberately for local/demo use only: {@code konecta.storage.public-
 * base-url} has to be reachable by whatever browser is doing the upload,
 * which only holds when the frontend and this service run on the same
 * machine (e.g. {@code http://localhost:8092}) — this does not work
 * against a real remote deployment. Switch {@code konecta.storage.provider}
 * back to {@code s3} once a paid AWS account is available again; nothing
 * else in this codebase needs to change.
 */
@Service
@ConditionalOnProperty(name = "konecta.storage.provider", havingValue = "local", matchIfMissing = true)
public class LocalFilesystemObjectStorageService implements ObjectStorageService {

    private final Path root;
    private final String publicBaseUrl;
    private final Duration putTtl;

    public LocalFilesystemObjectStorageService(
            @Value("${konecta.storage.local-dir}") String localDir,
            @Value("${konecta.storage.public-base-url}") String publicBaseUrl,
            @Value("${aws.s3.presign-put-ttl-seconds}") long putTtlSeconds) {
        this.root = Path.of(localDir).toAbsolutePath().normalize();
        this.publicBaseUrl = publicBaseUrl.replaceAll("/$", "");
        this.putTtl = Duration.ofSeconds(putTtlSeconds);
        try {
            Files.createDirectories(root);
        } catch (IOException e) {
            throw new IllegalStateException("Could not create local media storage directory: " + root, e);
        }
    }

    @Override
    public PresignedUpload presignUpload(String key, String contentType) {
        // No real signature — MediaController#put trusts any key shaped
        // like one S3KeyFactory would have issued (server-generated,
        // UUID-based) rather than verifying a signature, since there's no
        // presigner in play here. Fine for local/demo use; not a
        // substitute for S3's actual request-signing security model.
        return new PresignedUpload(publicBaseUrl + "/media/" + key, key, Instant.now().plus(putTtl));
    }

    @Override
    public boolean exists(String key) {
        return Files.exists(resolve(key));
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException e) {
            throw new IllegalStateException("Could not delete local media file: " + key, e);
        }
    }

    @Override
    public String presignDownload(String key) {
        return publicBaseUrl + "/media/" + key;
    }

    /**
     * Resolves a key to a path under {@link #root}, rejecting anything that
     * would escape it — keys are always server-generated by {@link
     * S3KeyFactory} in practice, but this is cheap insurance regardless.
     */
    Path resolve(String key) {
        Path resolved = root.resolve(key).normalize();
        if (!resolved.startsWith(root)) {
            throw new IllegalArgumentException("Invalid storage key: " + key);
        }
        return resolved;
    }

    Path root() {
        return root;
    }
}
